package_name: {{cookiecutter.package_name}}

# LOCAL DATA FILES
raw_data: example_data.xlsx
processed_data: processed_data.xlsx
train_data_file: training_data.xlsx
test_data_file: test_data.xlsx

# PIPELINE FILES
preprocess_pipeline_name: preprocessing_pipeline
analysis_pipeline_name: analysis_pipeline
preprocessing_pipeline_save_file: preprocessing_pipeline_output_v
analysis_pipeline_save_file: analysis_pipeline_output_v

# PACKAGE-LEVEL VARIABLE SPECIFICATIONS
targets:
  - q23_1

variables_to_include:
  - q23_1
  - q24_1
  - q5
  - q6
  - q8
  - q12


# PARAMETER SETTINGS
random_state: 42
test_size: 0.1
alpha: 0.05
variance_threshold: 0.01



# LOGISTIC REGRESSION MODEL SPECIFICATIONS
dependent_variable: q23_1

independent_variables:
  - q5
  - q6
  - q8
  - q12


# BINARY GRAPH SPECIFICATIONS
binary_graph_dependent_variables: 
  - q23_1

binary_graph_independent_variables:
  - q8